skillList = ["Adrenal Dexterity rank 1",
"Adrenal Dexterity rank 2",
"Adrenal Dexterity rank 3",
"Adrenal Dexterity rank 4",
"Adrenal Dexterity rank 5",
"Adrenal Dexterity rank 6",
"Adrenal Dexterity rank 7",
"Adrenal Dexterity rank 8",
"Adrenal Resist Fear rank 2",
"Adrenal Resist Immobility rank 3",
"Adrenal Resist Pain rank 4",
"Adrenal Strength rank 1",
"Adrenal Strength rank 3",
"Adrenal Strength rank 5",
"Buy Adrenals",
"Limit Raise Adrenals",
"Limit Raise Mastery Adrenals",
"Limit Raise Enhanced Mastery Adrenals",
"Limit Raise Superior Mastery Adrenals",
"Magic Tolerance",
"Use Adrenals Rank 1 - 8",
"Meditate Adrenals",
"Meditate Adrenals Mastery",
"Meditate Adrenals Enhanced Mastery",
"Meditate Adrenals Superior Mastery",
"Archer Acolyte",
"Archer Priest",
"Archer Specialist Acolyte - 1st Sect",
"Archer Specialist Priest - 1st Sect",
"Archer Specialist High Priest - 1st Sect",
"Archer Specialist Acolyte - 2nd Sect",
"Archer Specialist Priest - 2nd Sect",
"Archer Mage",
"Archer Wizard",
"Archer Specialist Mage - 1st School",
"Archer Specialist Wizard - 1st School",
"Archer Specialist Sorceror - 1st School",
"Archer Specialist Mage - 2nd School",
"Archer Specialist Wizard - 2nd School",
"Knockback Shot",
"Marksman",
"Missile Attunement",
"Missile Proficiency",
"Missile Mastery",
"Missile Enhanced Mastery",
"Speed Dart",
"Strength Attuned Bow",
"Nerve Strike Shot",
"Nerve Strike Shot Mastery",
"Nerve Strike Shot Enhanced Mastery",
"Armoured Dexterity",
"Unarmoured Dexterity",
"Armour Proficiency",
"Armour Mastery",
"Armour Enhanced Mastery",
"Armour Superior Mastery",
"Armour Exceptional Mastery",
"Armour Perfection",
"Shield Proficiency",
"Limit Raise Dexterity",
"Limit Raise Mastery Dexterity",
"Limit Raise Enhanced Mastery Dexterity",
"Limit Raise Superior Mastery Dexterity",
"Combat Awareness",
"Combat Awareness Mastery",
"Combat Awareness Enhanced Mastery",
"Combat Awareness Superior Mastery",
"Combat Awareness Exceptional Mastery",
"Additional Guild",
"Additional Class",
"Improved Empowering",
"Improved Ensorcelling",
"Increased Spirit Strength",
"Read / Write runes",
'Sworn to the King',
'Buy Ki',
'Focus Ki vs Magic',
'Focus Ki vs Power',
'Forearm Parry',
'Forearm Parry Mastery',
'Forearm Parry Enhanced Mastery',
'Use Ki',
'Limit Raise - Ki',
'Limit Raise Mastery - Ki',
'Limit Raise Enhanced Mastery - Ki',
'Limit Raise Superior Mastery - Ki',
'Meditate Ki',
'Meditate Ki Mastery',
'Meditate Ki Enhanced Mastery',
'Meditate Ki Superior Mastery',
'Ki Protection',
'Ki Protection Mastery',
'Ki Protection Enhanced Mastery',
'Ki Protection Superior Mastery',
'Recognise Magic',
'Buy Spell Slot level 1 (max 500 total mana)',
'Buy Spell Slot level 2 (max 500 total mana)',
'Buy Spell Slot level 3 (max 500 total mana)',
'Buy Spell Slot level 4 (max 500 total mana)',
'Buy Spell Slot level 5 (max 500 total mana)',
'Buy Spell Slot level 6 (max 500 total mana)',
'Buy Spell Slot level 7 (max 500 total mana)',
'Buy Spell Slot level 8 (max 500 total mana)',
'Buy Spell Slot level 9 (max 500 total mana)',
'Buy Spell Slot level 10 (max 500 total mana)',
'Cast two colours of Magic levels 1 - 5',
'Cast additional colour of Magic 3 &4 - levels 1 - 5',
'Cast additional colour of Magic 5 & 6 -  levels 1 - 5',
'Cast 7th colour of Magic levels 1 - 5',
'Cast 8th colour of Magic levels 1 - 5',
'Make Focus',
'Cast Wizardry (6-8) in Black',
'Cast Wizardry (6-8) in Blue',
'Cast Wizardry (6-8) in Brown',
'Cast Wizardry (6-8) in Green',
'Cast Wizardry (6-8) in Grey',
'Cast Wizardry (6-8) in Red',
'Cast Wizardry (6-8) in White',
'Cast Wizardry (6-8) in Yellow',
'Make Arcane Focus',
'Cast Arcane (9-10) in Black',
'Cast Arcane (9-10) in Blue',
'Cast Arcane (9-10) in Brown',
'Cast Arcane (9-10) in Green',
'Cast Arcane (9-10) in Grey',
'Cast Arcane (9-10) in Red',
'Cast Arcane (9-10) in White',
'Cast Arcane (9-10) in Yellow',
'Learn additional Spells level 1 - 8',
'Learn level 9 spells',
'Learn Level 10 spells',
'Limit Raise - Mana',
'Limit Raise Mastery - Mana',
'Limit Raise Enhanced Mastery - Mana',
'Limit Raise Superior Mastery - Mana',
'Limit Raise - Spell',
'Mnemonic',
'Mnemonic Mastery',
'Mnemonic Enhanced Mastery',
'Mnemonic Superior Mastery',
'Mnemonic Attunement',
'Recharge Active Spell',
'Spell Store',
'Recast Spell Store',
'Elemental Proficiency',
'Elemental Mastery',
'Elemental Enhanced Mastery',
'Elemental Superior Mastery',
'Extra Arcane Store Preparation',
'Exceptional Arcane Store Preparation',
'Spell Extension',
'Write Battle Magic Scrolls',
'Write High Magic Scrolls',
'Write Arcane Magic Scrolls',
'Discern Wounds',
'Field Medicine',
'First Aid',
'Set Broken Bone',
'Discern Disease',
'Discern Paralysis',
'Discern Poisoning',
'Discern Spiritual Influence',
'Buy Life points (3 at a time)',
'Ambidexterity Mastery',
'Strength',
'Strength - Double',
'Strength - Triple',
'Toughened Skin',
'Toughened Skin Mastery',
'Toughened Skin Enhanced Mastery',
'Toughened Skin Superior Mastery',
'Alchemist',
'Additional Alchemical Recipes',
'Transmutation',
'Transmutation Mastery',
'Transmutation Enhanced Mastery',
"Philosopher's Stone",
"Philosopher's Stone Mastery",
"Philosopher's Stone Enhanced Mastery",
'Construct Laboratory',
'Construct Laboratory Mastery',
'Construct Laboratory Enhanced Mastery',
'Construct Laboratory Superior Mastery',
'Potion Master',
'Poison Master',
'Herbalist',
'Make Herbal Potion',
'Make Herbal Potion Mastery',
'Make Herbal Potion Enhanced Mastery',
'Make Herbal Potion Superior Mastery',
'Make Herbal Potion Exceptional Mastery',
'Alembic',
'Master Alembic',
'Prescision Alembic',
'Distil Herbal Potion',
'Distil Herbal Potion Mastery',
'Distil Herbal Potion Enhanced Mastery',
'Buy Power',
'Meditate Power',
'Meditate Power Mastery',
'Meditate Power Enhanced Mastery',
'Meditate Power Superior Mastery',
'Power Store - Lesser',
'Power Store - Greater',
'Recognise Power',
'Connection with 1st Sphere',
'Cast 1st Sphere ranks 1 - 5',
'Cast 1st Sphere ranks 6 - 8',
'Cast 1st Sphere ranks 9 - 10',
'Connection with 2nd Sphere',
'Cast 2nd Sphere ranks 1 - 5',
'Cast 2nd Sphere ranks 6 - 8',
'Cast 2nd Sphere ranks 9 - 10',
'Connection with 3rd Sphere',
'Cast 3rd Sphere ranks 1 - 5',
'Cast 3rd Sphere ranks 6 - 8',
'Cast 3rd Sphere ranks 9 - 10',
'Greater Invoke',
'Invocation Guard',
'Invoke Mastery',
'Invocation Extension',
'Learn additional rank 1 - 8 Invocations',
'Learn rank 9 Invocations',
'Learn rank 10 Invocations',
'Limit Raise - Power',
'Limit Raise Mastery - Power',
'Limit Raise Enhanced Mastery - Power',
'Limit Raise Superior Mastery - Power',
'Limit Raise - Invocation',
'Make Talisman',
'Priest in 2nd Sphere',
'Priest in 3rd Sphere',
'Cast Cosmic Power in Additional Sphere',
'Cast Cosmic Power in 1st Sphere',
'Write Lay Power Scrolls',
'Write Ritual Power Scrolls',
'Write Cosmic Power Scrolls',
'Limit Raise - Psi',
'Limit Raise Mastery - Psi',
'Limit Raise Enhanced Mastery - Psi',
'Meditate Psi',
'Meditate Psi Mastery',
'Meditate Psi Enhanced Mastery',
'Meditate Psi Superior Mastery',
'Buy Psi',
'Cast Rank Psi',
'Make Psi Talisman',
'Dodge - Uncanny',
'Dodge - Exceptional',
'Dodge - Superior',
'Jack of All trades',
'Trap Handling',
'Trap Handling Mastery',
'Trap Handling Enhanced Mastery',
'Trap Handling Superior Mastery',
'Trap Handling Exceptional Mastery',
'Disguise',
'Disguise Mastery',
'Disguise Other',
'Recognise Disguise',
'Recognise Disguise Mastery',
'Sneak Attack',
'Sneak Attack Mastery',
'Sneak Attack Enhanced Mastery',
'Sneak Attack Superior Mastery',
'Sneak Attack Exceptional Mastery',
'Throat Slit',
'Throat Slit Mastery',
'Throat Slit Enhanced Mastery',
'Throat Slit Superior Mastery',
'Throat Slit Exceptional Mastery',
'Bonebreak',
'Bonebreak Mastery',
'Bonebreak Enhanced Mastery',
'Bonebreak Superior Mastery',
'Damage Increase',
'Damage Increase Mastery',
'Disarm - Uses',
'Disarm',
'Disarm Mastery',
'Disarm Enhanced Mastery',
'Disarm Superior Mastery',
'Dismember',
'Dismember Mastery',
'Dismember Enhanced Mastery',
'Dismember Superior Mastery',
'Hold the Line',
'Hold the Line Mastery',
'Hold the Line Enhanced Mastery',
'Never Surrender',
'Never Say Die',
'External Champion',
'Knockback Uses',
'Knockback',
'Knockback Mastery',
'Knockback Enhanced Mastery',
'Knockback Superior Mastery',
'Knockdown Uses',
'Knockdown',
'Knockdown Mastery',
'Knockdown Enhanced Mastery',
'Knockdown Superior Mastery',
'Limit Raise - Life',
'Limit Raise Mastery - Life',
'Limit Raise Enhanced Mastery - Life',
'Limit Raise Superior Mastery - Life',
'Nerve Strike Uses',
'Nerve Strike',
'Nerve Strike Mastery',
'Nerve Strike Enhanced Mastery',
'Nerve Strike Superior Mastery',
'Resist Bonebreak',
'Resist Bonebreak Mastery',
'Resist Bonebreak Enhanced Mastery',
'Resist Bonebreak Superior Mastery',
'Resist Disarm',
'Resist Disarm Mastery',
'Resist Disarm Enhanced Mastery',
'Resist Disarm Superior Mastery',
'Resist Dismember',
'Resist Dismember Mastery',
'Resist Dismember Enhanced Mastery',
'Resist Dismember Superior Mastery',
'Resist Knockback',
'Resist Knockback Mastery',
'Resist Knockback Enhanced Mastery',
'Resist Knockback Superior Mastery',
'Resist Knockdown',
'Resist Knockdown Mastery',
'Resist Knockdown Enhanced Mastery',
'Resist Knockdown Superior Mastery',
'Resist Nerve Strike',
'Resist Nerve Strike Mastery',
'Resist Nerve Strike Enhanced Mastery',
'Resist Nerve Strike Superior Mastery',
'Resist Shield Arm Bonebreak',
'Resist Shield Arm Bonebreak Mastery',
'Resist Shield Arm Bonebreak Enhanced Mastery',
'Resist Shield Cleave',
'Resist Shield Cleave Mastery',
'Resist Shield Cleave Enhanced Mastery',
'Resist Through Damage',
'Resist Through Damage Mastery',
'Resist Through Damage Enhanced Mastery',
'Shield Arm Bonebreak',
'Shield Arm Bonebreak Mastery',
'Shield Arm Bonebreak Enhanced Mastery',
'Shield Cleave',
'Shield Cleave Mastery',
'Shield Cleave Enhanced Mastery',
'Shield Cleave Superior Mastery',
'Spiritual Warrior',
'Spiritual Warrior Mastery',
'Spiritual Warrior Enhanced Mastery',
'Subdual',
'Subdual Mastery',
'Subdual Enhanced Mastery',
'Sunder',
'Sunder Mastery',
'Sunder Enhanced Mastery',
'Cast through Weapon',
'Cast through Weapon Mastery',
'Weapon Bond',
'Weapon Proficiency - Single handed (blunt and sharp)',
'Weapon Mastery - Single handed (blunt / sharp)',
'Weapon Enhanced Mastery - Single handed (blunt/sharp)',
'Dagger Proficiency',
'Dagger Mastery',
'Dagger Enhanced Mastery',
'Weapon Proficiency - Double handed (blunt and sharp)',
'Weapon Mastery - Double handed (blunt / sharp)',
'Weapon Enhanced Mastery - Double handed (blunt/sharp)',
'Weapon Attunement (single sharp/blunt; double sharp/blunt; dagger)',
'Class Upgrade - Class Secondary to Primary',
'Class Upgrade - Class Secondary 2 to Primary' ,
'Class Upgrade - Class Secondary 3 to Primary',
'Class Upgrade - Class Secondary 4 to Primary',
'Class Upgrade - Class Secondary 5 to Primary',
'Class Upgrade - Class Secondary 6 to Primary',
'Class Upgrade - Class Secondary 7 to Primary',
'Guild Upgrade - Additional Class Secondary to Primary',
'Guild Upgrade - Additional Class 2 Secondary to Primary',
'Has Purple Magic' ,
'Is Dedicated',]

['Weakness', 
 'Weakness 6', 
 'Weakness Store 6', 
 'Weakness Store 7', 
 'Weakness Store 8', 
 'Mass Weakness 8', 
 'Hand of Darkness 7', 
 'Hand of Darkness 8', 
 'Blindness 1 to 5', 
 'Blindness 6', 
 'Blindness 7', 
 'Blindness 8', 
 'Blindness 9', 
 'Blindness 10', 
 'Strength Stealer 9', 
 'Strength Stealer 10', 
 'Dark Bolt 6', 
 'Dark Bolt 7', 
 'Dark Bolt 8', 
 'Dark Skin 6', 
 'Dark Skin 7', 
 'Dark Skin 8', 
 'Dark Skin 9', 
 'Dark Skin 10', 
 'Armour of Darkenss 9', 
 'Armour of Darkenss 10', 
 'Dark Store 6', 
 'Dark Store 7', 
 'Dark Store 8', 
 'Dark Shield 8', 
 'Embody Elemental of Darkness 6', 
 'Embody Elemental of Darkness 7', 
 'Embody Elemental of Darkness 8', 
 'Afinity to Darkness 9', 
 'Afinity to Darkness 10', 
 'Sight Stealer 9', 
 'Sight Stealer 10', 
 'Repulsion', 
 'Repulsion Store 6', 
 'Repulsion Store 7', 
 'Repulsion Store 8', 
 'Clear Skies 6', 
 'Clear Skies 7', 
 'Clear Skies 8', 
 'Dumbness 1 to 5', 
 'Dumbness 6', 
 'Dumbness 7', 
 'Dumbness 8', 
 'Dumbness 9', 
 'Dumbness 10', 
 'Blink 10', 
 'Teleport 1 to 5', 
 'Teleport 6', 
 'Teleport 7', 
 'Teleport 8', 
 'Teleport 9', 
 'Teleport 10', 
 'Teleport Ward 6', 
 'Teleport Ward 7', 
 'Teleport Ward 8', 
 'Forced Teleport 8',
  'Air Wall 6', 
  'Air Wall 7', 
  'Air Wall 8', 
  'Shield of Air 6', 
  'Shield of Air 7', 
  'Shield of Air 8', 
  'Shield of Air 9', 
  'Shield of Air 10', 
  'Sleep 6', 
  'Sleep 7', 
  'Sleep 8', 
  'Sleep 9', 
  'Sleep 10', 
  'Sleep Store 6', 
  'Sleep Store 7', 
  'Sleep Store 8', 
  'Embody Air Elemental 6', 
  'Embody Air Elemental 7', 
  'Embody Air Elemental 8', 
  'Thunderclap 7', 
  'Whirlwind 6', 
  'Whirlwind 7', 
  'Whirlwind 8', 
  'Whispering Wind 8', 
  'Affinity to Air 9', 
  'Affinity to Air 10', 
  'Master of Winds 9', 
  'Master of Winds 10',
  'Shield of the Hurricane 9', 
  'Shield of the Hurricane 10', 
  'Walk on Air 6', 
  'Walk on Air 7', 
  'Walk on Air 8', 
  'Walk on Air 9',
  'Walk on Air 10', 
  'Weld', 
  'Mass Weld 8',
  'Mass Bind 6',
  'Magic Missile 6',
  'Magic Missile 7', 
  'Magic Missile 8', 
  'Magic Missile Store 6', 
  'Magic Missile Store 7', 
  'Magic Missile Store 8',
  'Sanctuary of Earth 1 to 5', 
  'Santuary of Earth 6', 
  'Santuary of Earth 7', 
  'Santuary of Earth 8', 
  'Protection from Earthquake 4, 5', 
  'Earthquake 8', 
  'Embody Earth Elemental 6', 
  'Embody Earth Elemental 7', 
  'Embody Earth Elemental 8', 
  'Entrapment 6', 
  'Entrapment 7', 
  'Entombment 9', 
  'Entombment 10', 
  'Rock Skin 7', 
  'Affinity to Earth 9', 
  'Affinity to Earth 10', 
  'Assault of Stone 9', 
  'Assault of Stone 10', 
  'Bastion of Earth 9', 
  'Bastion of Earth 10', 
  'Stone Form 6', 
  'Stone Form 7', 
  'Stone Form 8', 
  'Stone Form 9', 
  'Stone Form 10', 
  'Stone Crafter 9', 
  'Stone Crafter 10', 
  'Slow', 
  'Slow 6', 
  'Slow Store 6', 
  'Slow Store 7', 
  'Slow Store 8', 
  'Mass Slow 8', 
  'Mass Slip', 
  'Recall 6', 
  'Recall 7', 
  'Recall 8', 
  'Recall 9', 
  'Recall 10', 
  'Spell Store 6', 
  'Spell Store 7', 
  'Spell Store 8', 
  'Enchant Spell Store 6', 
  'Enchant Spell Store 7', 
  'Enchant Spell Store 8', 
  "Wizard's Gift 6", 
  "Wizard's Gift 7", 
  "Wizard's Gift 8", 
  'Guided by the Stars 10', 
  'Identify 6', 
  'Identify 7', 
  'Identify 8', 
  'Embody Water Elemental 6', 
  'Embody Water Elemental 7', 
  'Embody Water Elemental 8', 
  'Vanish Animate 6', 
  'Vanish Animate 7', 
  'Vanish Animate 8', 
  'Vanish Inanimate 6', 
  'Vanish Inanimate 7', 
  'Vanish Inanimate 8', 
  'Affinity to Water 9', 
  'Affinity to Water 10', 
  'Contingency 6', 
  'Contingency 7', 
  'Contingency 8', 
  'Contingency 9', 
  'Contingency 10', 
  "Sorcerer's Store 9", 
  "Sorcerer's Store 10", 
  "Sorcerer's Gift 9", 
  "Sorcerer's Gift 10", 
  "Sorcerer's Memonic 9", 
  "Sorcerer's Memonic 10", 
  'Cast in Armour', 
  'Shield 2, 4', 
  'Warlocks Blade 2, 4', 
  'Combat Readiness 6', 
  'Combat Readiness 7', 
  'Combat Readiness 8', 
  'Peerless Combatant 9', 
  'Peerless Combatant 10', 
  'Double Strength 6', 
  'Double Strength 7', 
  'Endurance 6', 
  'Endurance 7', 
  'Endurance 8', 
  'Mass Endurance 6', 
  'Mass Endurance 7', 
  'Mass Endurance 8', 
  'Mass Endurance 9', 
  'Mass Endurance 10', 
  'Enduring Vigor 9', 
  'Enduring Vigor 10', 
  'Protection from Weakness 6', 
  'Protection from Weakness 7', 
  'Protection from Weakness 8', 
  'Weapon Proficiency 6', 
  'Weapon Proficiency 7', 
  'Weapon Proficiency 8', 
  'Embody Steel Elemental 6', 
  'Embody Steel Elemental 7', 
  'Embody Steel Elemental 8', 
  'Continuous Casting 6', 
  'Continuous Casting 7', 
  'Continuous Casting 8', 
  'Affinty to Steel 9', 
  'Affinity to Steel 10', 
  'Blade Ward 9', 
  'Protection from Battle Magic 6', 
  'Protection from Battle Magic 7', 
  'Protection from Battle Magic 8', 
  'Shield of Steel 6', 
  'Shield of Steel 7', 
  'Shield of Steel 8', 
  'Plate on Plate 7 ', 
  'Plate on Plate 8', 
  'Perfect Steel 9 ', 
  'Resilience 10 ', 
  "Warlock's Armoury 9", 
  "Warlock's Armoury 10", 
  'Magma Blade', 
  'Flame Blade 6', 
  'Flame Blade 7', 
  'Flame Blade 8', 
  'Flame Blade 9', 
  'Flame Blade 10', 
  'Burning Blade 4 to 5', 
  'Burning Blade 6', 
  'Burning Blade 7', 
  'Burning Blade 8', 
  'Blade Bond 5', 
  'Blade Bond 6', 
  'Blade Bond 7', 
  'Blade Bond 8', 
  'Blade Ward 9', 
  'Fire Brand 1  to  5', 
  'Embody Elemental of Fire 6', 
  'Embody Elemental of Fire 7', 
  'Embody Elemental of Fire 8', 
  'Bolt Store 6', 
  'Bolt Store 7', 
  'Bolt Store 8', 
  'Fire Bolt 6', 
  'Fire Bolt 7', 
  'Fire Bolt 8', 
  'Fire Skin 6', 
  'Fire Skin 7', 
  'Fire Skin 8', 
  'Fire Skin 9', 
  'Fire Skin 10', 
  'Meltdown 6', 
  'Meltdown 7', 
  'Finger of Flame 5', 
  'Finger of Flame 6', 
  'Finger of Flame 7', 
  'Finger of Flame 8', 
  'Pillar of Flame 6', 
  'Pillar of Flame 7', 
  'Pillar of Flame 8', 
  'Pillar of Flame 9', 
  'Pillar of Flame 10', 
  'Furious Fire 5', 
  'Furious Fire 6', 
  'Furious Fire 7', 
  'Furious Fire 8', 
  'Flame Store 6', 
  'Flame Store 7', 
  'Flame Store 8', 
  'Affinity to Fire 9', 
  'Affinity to Fire 10', 
  'Flame Shaper 9', 
  'Flame Shaper 10', 
  'Inner Fire 9', 
  'Inner Fire 10', 
  'Fusillade of Flame 9', 
  'Fusillade of Flame 10', 
  'Freeze 4, 5', 
  'Deep Freeze 5', 
  'Mass Freeze 8', 
  'Mass Flash 5', 
  'Fumble 4, 5', 
  'Mass Fumble 7', 
  'Staff of Ice 3', 
  'Staff of Ice 6', 
  'Staff of Ice 7', 
  'Staff of Ice 8', 
  'Clear Sight 6', 
  'Clear Sight 7', 
  'Ice Javelin 6', 
  'Ice Javelin 7', 
  'Ice Javelin 8', 
  'Staff of Ice 6', 
  'Staff of Ice 7', 
  'Staff of Ice 8', 
  'Cone of Cold 6', 
  'Cone of Cold 7', 
  'Cone of Cold 8', 
  'Cryostasis 6', 
  'Cryostasis 7', 
  'Frostbite 6', 
  'Frostbite 7', 
  'Ice Store 6', 
  'Ice Store 7', 
  'Ice Store 8', 
  'Immunity to Cold 6', 
  'Immunity to Cold 7', 
  'Immunity to Cold 8', 
  'Hoarfrost 9', 
  'Hoarfrost 10', 
  'Affinity to Light 9', 
  'Affinity to Light 10', 
  'Vessel of Light 9', 
  'Vessel of Light 10', 
  'Embody Elemental of Ice 6', 
  'Embody Elemental of Ice 7', 
  'Embody Elemental of Ice 8', 
  'Frost Weaver 9', 
  'Frost Weaver 10', 
  'Frozen Storm 9', 
  'Frozen Storm 10', 
  'Forked Grasp 5', 
  'Forked Grasp 6', 
  'Forked Grasp 7', 
  'Forked Grasp 8', 
  'Lightning Bolt 6', 
  'Lightning Bolt 7', 
  'Lightning Bolt 8', 
  'Static Field 6', 
  'Static Field 7', 
  'Static Field 8', 
  'Static Field 9', 
  'Static Field 10', 
  'Mass Static Field 6', 
  'Mass Static Field 7', 
  'Mass Static Field 8', 
  'Radial Static Field 6', 
  'Radial Static Field 7', 
  'Radial Static Field 8', 
  'Radial Static Field 9', 
  'Radial Static Field 10', 
  'Shocking Grasp 6', 
  'Shocking Grasp 7', 
  'Shocking Grasp 8', 
  'Chain Lightning 6', 
  'Chain Lightning 7', 
  'Chain Lightning 8', 
  'Chain Lightning 9', 
  'Chain Lightning 10', 
  'Charge Animate 6', 
  'Charge Animate 7', 
  'Charge Animate 8', 
  'Charge Self 9', 
  'Charge Self 10', 
  'Electify Weapon 6', 
  'Electify Weapon 7', 
  'Electify Weapon 8', 
  'Lightning Store 6', 
  'Lightning Store 7', 
  'Lightning Store 8', 
  'Stun 6', 
  'Stun 7', 
  'Stun Store 9', 
  'Stun Store 10', 
  'Affinity to Storms 9', 
  'Affinity to Storms 10', 
  'Storm Caller 9', 
  'Storm Caller 10', 
  'Tempest 9', 
  'Tempest 10', 
  'Embody Elemental of Lightning 6', 
  'Embody Elemental of Lightning 7', 
  'Embody Elemental of Lightning 8', 
  'Dispel Magic 6', 
  'Dispel Magic 7', 
  'Dispel Magic 8', 
  'Wizards Dispel 6', 
  'Sorcerers Dispel 9', 
  'Sorcerers Dispel 10', 
  'Affinity to Magic 9', 
  'Affinity to Magic 10', 
  'Elemental Vessel 5', 
  'Elemental Vessel 8', 
  'Mana Suppression 1-5', 
  'Mana Suppression 6', 
  'Mana Suppression 7', 
  'Mana Suppression 8', 
  'Mana Suppression 9', 
  'Mana Suppression 10', 
  'Permanency 10', 
  'Spell Extension 1-5', 
  'Spell Extension 6', 
  'Spell Extension 7', 
  'Spell Extension 8', 
  'Spell Extension 9', 
  'Spell Extension 10', 
  'Spell Guard 1-5', 
  'Spell Guard 6', 
  'Spell Guard 7', 
  'Spell Guard 8', 
  'Spell Guard 9', 
  'Spell Guard 10', 
  'Flashing Blade 5', 
  'Flashing Blade 5', 
  'Quicksand 5', 
  'Grounding 5', 
  'Grounding 5', 
  'Permafrost 5', 
  'Burning Hands 5', 
  'Blinding Bolt 5',]

raceClassDict = {1  : {'race' : 'human', 'class' : 'Warrior'},
                 2  : {'race' : 'human', 'class' : 'Scout'},
                 3  : {'race' : 'human', 'class' : 'Acolyte Good'},
                 4  : {'race' : 'human', 'class' : 'Acolyte Neutral'},
                 5  : {'race' : 'human', 'class' : 'Acolyte Evil'},
                 6  : {'race' : 'human', 'class' : 'Mage'},
                 7  : {'race' : 'elf', 'class' : 'Warrior'},
                 8  : {'race' : 'elf', 'class' : 'Scout'},
                 9  : {'race' : 'elf', 'class' : 'Acolyte Good'},
                 10 : {'race' : 'elf', 'class' : 'Acolyte Neutral'},
                 11 : {'race' : 'elf', 'class' : 'Acolyte Evil'},
                 12 : {'race' : 'elf', 'class' : 'Mage'},
                 13 : {'race' : 'half-orc', 'class' : 'Warrior'},
                 14 : {'race' : 'half-orc', 'class' : 'Scout'},
                 15 : {'race' : 'half-orc', 'class' : 'Acolyte Good'},
                 16 : {'race' : 'half-orc', 'class' : 'Acolyte Neutral'},
                 17 : {'race' : 'half-orc', 'class' : 'Acolyte Evil'},
                 18 : {'race' : 'half-orc', 'class' : 'Mage'},}

guildList = ['Sentinel',
             'Reaver',
             'Barbarian',
             'Paladin',
             'Skirmisher',
             'Monk',
             'Assassin',
             'Archer',
             'Black School',
             'Blue School',
             'Brown School',
             'Green School',
             'Grey School',
             'Red School',
             'White School',
             'Yellow School',
             'White Path',
             'Hospitaller',
             'Humacti',
             'Michelene',
             'Grey Path',
             'Warden',
             'Gauntlet',
             'Druid',
             'Dark Path',
             'Seer',
             'Brethren',
             'Reaper',
             'None']