skillList = ["Adrenal Dexterity rank 1",
"Adrenal Dexterity rank 2",
"Adrenal Dexterity rank 3",
"Adrenal Dexterity rank 4",
"Adrenal Dexterity rank 5",
"Adrenal Dexterity rank 6",
"Adrenal Dexterity rank 7",
"Adrenal Dexterity rank 8",
"Adrenal Resist Fear rank 2",
"Adrenal Resist Immobility rank 3",
"Adrenal Resist Pain rank 4",
"Adrenal Strength rank 1",
"Adrenal Strength rank 3",
"Adrenal Strength rank 5",
"Buy Adrenals",
"Limit Raise Adrenals",
"Limit Raise Mastery Adrenals",
"Limit Raise Enhanced Mastery Adrenals",
"Limit Raise Superior Mastery Adrenals",
"Magic Tolerance",
"Use Adrenals Rank 1 - 8",
"Meditate Adrenals",
"Meditate Adrenals Mastery",
"Meditate Adrenals Enhanced Mastery",
"Meditate Adrenals Superior Mastery",
"Archer Acolyte",
"Archer Priest",
"Archer Specialist Acolyte - 1st Sect",
"Archer Specialist Priest - 1st Sect",
"Archer Specialist High Priest - 1st Sect",
"Archer Specialist Acolyte - 2nd Sect",
"Archer Specialist Priest - 2nd Sect",
"Archer Mage",
"Archer Wizard",
"Archer Specialist Mage - 1st School",
"Archer Specialist Wizard - 1st School",
"Archer Specialist Sorceror - 1st School",
"Archer Specialist Mage - 2nd School",
"Archer Specialist Wizard - 2nd School",
"Knockback Shot",
"Marksman",
"Missile Attunement",
"Missile Proficiency",
"Missile Mastery",
"Missile Enhanced Mastery",
"Speed Dart",
"Strength Attuned Bow",
"Nerve Strike Shot",
"Nerve Strike Shot Mastery",
"Nerve Strike Shot Enhanced Mastery",
"Armoured Dexterity",
"Unarmoured Dexterity",
"Armour Proficiency",
"Armour Mastery",
"Armour Enhanced Mastery",
"Armour Superior Mastery",
"Armour Exceptional Mastery",
"Armour Perfection",
"Shield Proficiency",
"Limit Raise Dexterity",
"Limit Raise Mastery Dexterity",
"Limit Raise Enhanced Mastery Dexterity",
"Limit Raise Superior Mastery Dexterity",
"Combat Awareness",
"Combat Awareness Mastery",
"Combat Awareness Enhanced Mastery",
"Combat Awareness Superior Mastery",
"Combat Awareness Exceptional Mastery",
"Additional Guild",
"Additional Class",
"Improved Empowering",
"Improved Ensorcelling",
"Increased Spirit Strength",
"Read / Write runes",
'Sworn to the King',
'Buy Ki',
'Focus Ki vs Magic',
'Focus Ki vs Power',
'Forearm Parry',
'Forearm Parry Mastery',
'Forearm Parry Enhanced Mastery',
'Use Ki',
'Limit Raise - Ki',
'Limit Raise Mastery - Ki',
'Limit Raise Enhanced Mastery - Ki',
'Limit Raise Superior Mastery - Ki',
'Meditate Ki',
'Meditate Ki Mastery',
'Meditate Ki Enhanced Mastery',
'Meditate Ki Superior Mastery',
'Ki Protection',
'Ki Protection Mastery',
'Ki Protection Enhanced Mastery',
'Ki Protection Superior Mastery',
'Recognise Magic',
'Buy Spell Slot level 1 (max 500 total mana)',
'Buy Spell Slot level 2 (max 500 total mana)',
'Buy Spell Slot level 3 (max 500 total mana)',
'Buy Spell Slot level 4 (max 500 total mana)',
'Buy Spell Slot level 5 (max 500 total mana)',
'Buy Spell Slot level 6 (max 500 total mana)',
'Buy Spell Slot level 7 (max 500 total mana)',
'Buy Spell Slot level 8 (max 500 total mana)',
'Buy Spell Slot level 9 (max 500 total mana)',
'Buy Spell Slot level 10 (max 500 total mana)',
'Cast two colours of Magic levels 1 - 5',
'Cast additional colour of Magic 3 &4 - levels 1 - 5',
'Cast additional colour of Magic 5 & 6 -  levels 1 - 5',
'Cast 7th colour of Magic levels 1 - 5',
'Cast 8th colour of Magic levels 1 - 5',
'Make Focus',
'Cast Wizardry (6-8) in Black',
'Cast Wizardry (6-8) in Blue',
'Cast Wizardry (6-8) in Brown',
'Cast Wizardry (6-8) in Green',
'Cast Wizardry (6-8) in Grey',
'Cast Wizardry (6-8) in Red',
'Cast Wizardry (6-8) in White',
'Cast Wizardry (6-8) in Yellow',
'Make Arcane Focus',
'Cast Arcane (9-10) in Black',
'Cast Arcane (9-10) in Blue',
'Cast Arcane (9-10) in Brown',
'Cast Arcane (9-10) in Green',
'Cast Arcane (9-10) in Grey',
'Cast Arcane (9-10) in Red',
'Cast Arcane (9-10) in White',
'Cast Arcane (9-10) in Yellow',
'Learn additional Spells level 1 - 8',
'Learn level 9 spells',
'Learn Level 10 spells',
'Limit Raise - Mana',
'Limit Raise Mastery - Mana',
'Limit Raise Enhanced Mastery - Mana',
'Limit Raise Superior Mastery - Mana',
'Limit Raise - Spell',
'Mnemonic',
'Mnemonic Mastery',
'Mnemonic Enhanced Mastery',
'Mnemonic Superior Mastery',
'Mnemonic Attunement',
'Recharge Active Spell',
'Spell Store',
'Recast Spell Store',
'Elemental Proficiency',
'Elemental Mastery',
'Elemental Enhanced Mastery',
'Elemental Superior Mastery',
'Extra Arcane Store Preparation',
'Exceptional Arcane Store Preparation',
'Spell Extension',
'Write Battle Magic Scrolls',
'Write High Magic Scrolls',
'Write Arcane Magic Scrolls',
'Discern Wounds',
'Field Medicine',
'First Aid',
'Set Broken Bone',
'Discern Disease',
'Discern Paralysis',
'Discern Poisoning',
'Discern Spiritual Influence',
'Buy Life points (3 at a time)',
'Ambidexterity Mastery',
'Strength',
'Strength - Double',
'Strength - Triple',
'Toughened Skin',
'Toughened Skin Mastery',
'Toughened Skin Enhanced Mastery',
'Toughened Skin Superior Mastery',
'Alchemist',
'Additional Alchemical Recipes',
'Transmutation',
'Transmutation Mastery',
'Transmutation Enhanced Mastery',
"Philosopher's Stone",
"Philosopher's Stone Mastery",
"Philosopher's Stone Enhanced Mastery",
'Construct Laboratory',
'Construct Laboratory Mastery',
'Construct Laboratory Enhanced Mastery',
'Construct Laboratory Superior Mastery',
'Potion Master',
'Poison Master',
'Herbalist',
'Make Herbal Potion',
'Make Herbal Potion Mastery',
'Make Herbal Potion Enhanced Mastery',
'Make Herbal Potion Superior Mastery',
'Make Herbal Potion Exceptional Mastery',
'Alembic',
'Master Alembic',
'Prescision Alembic',
'Distil Herbal Potion',
'Distil Herbal Potion Mastery',
'Distil Herbal Potion Enhanced Mastery',
'Buy Power',
'Meditate Power',
'Meditate Power Mastery',
'Meditate Power Enhanced Mastery',
'Meditate Power Superior Mastery',
'Power Store - Lesser',
'Power Store - Greater',
'Recognise Power',
'Connection with 1st Sphere',
'Cast 1st Sphere ranks 1 - 5',
'Cast 1st Sphere ranks 6 - 8',
'Cast 1st Sphere ranks 9 - 10',
'Connection with 2nd Sphere',
'Cast 2nd Sphere ranks 1 - 5',
'Cast 2nd Sphere ranks 6 - 8',
'Cast 2nd Sphere ranks 9 - 10',
'Connection with 3rd Sphere',
'Cast 3rd Sphere ranks 1 - 5',
'Cast 3rd Sphere ranks 6 - 8',
'Cast 3rd Sphere ranks 9 - 10',
'Greater Invoke',
'Invocation Guard',
'Invoke Mastery',
'Invocation Extension',
'Learn additional rank 1 - 8 Invocations',
'Learn rank 9 Invocations',
'Learn rank 10 Invocations',
'Limit Raise - Power',
'Limit Raise Mastery - Power',
'Limit Raise Enhanced Mastery - Power',
'Limit Raise Superior Mastery - Power',
'Limit Raise - Invocation',
'Make Talisman',
'Priest in 2nd Sphere',
'Priest in 3rd Sphere',
'Cast Cosmic Power in Additional Sphere',
'Cast Cosmic Power in 1st Sphere',
'Write Lay Power Scrolls',
'Write Ritual Power Scrolls',
'Write Cosmic Power Scrolls',
'Limit Raise - Psi',
'Limit Raise Mastery - Psi',
'Limit Raise Enhanced Mastery - Psi',
'Meditate Psi',
'Meditate Psi Mastery',
'Meditate Psi Enhanced Mastery',
'Meditate Psi Superior Mastery',
'Buy Psi',
'Cast Rank Psi',
'Make Psi Talisman',
'Dodge - Uncanny',
'Dodge - Exceptional',
'Dodge - Superior',
'Jack of All trades',
'Trap Handling',
'Trap Handling Mastery',
'Trap Handling Enhanced Mastery',
'Trap Handling Superior Mastery',
'Trap Handling Exceptional Mastery',
'Disguise',
'Disguise Mastery',
'Disguise Other',
'Recognise Disguise',
'Recognise Disguise Mastery',
'Sneak Attack',
'Sneak Attack Mastery',
'Sneak Attack Enhanced Mastery',
'Sneak Attack Superior Mastery',
'Sneak Attack Exceptional Mastery',
'Throat Slit',
'Throat Slit Mastery',
'Throat Slit Enhanced Mastery',
'Throat Slit Superior Mastery',
'Throat Slit Exceptional Mastery',
'Bonebreak',
'Bonebreak Mastery',
'Bonebreak Enhanced Mastery',
'Bonebreak Superior Mastery',
'Damage Increase',
'Damage Increase Mastery',
'Disarm - Uses',
'Disarm',
'Disarm Mastery',
'Disarm Enhanced Mastery',
'Disarm Superior Mastery',
'Dismember',
'Dismember Mastery',
'Dismember Enhanced Mastery',
'Dismember Superior Mastery',
'Hold the Line',
'Hold the Line Mastery',
'Hold the Line Enhanced Mastery',
'Never Surrender',
'Never Say Die',
'External Champion',
'Knockback Uses',
'Knockback',
'Knockback Mastery',
'Knockback Enhanced Mastery',
'Knockback Superior Mastery',
'Knockdown Uses',
'Knockdown',
'Knockdown Mastery',
'Knockdown Enhanced Mastery',
'Knockdown Superior Mastery',
'Limit Raise - Life',
'Limit Raise Mastery - Life',
'Limit Raise Enhanced Mastery - Life',
'Limit Raise Superior Mastery - Life',
'Nerve Strike Uses',
'Nerve Strike',
'Nerve Strike Mastery',
'Nerve Strike Enhanced Mastery',
'Nerve Strike Superior Mastery',
'Resist Bonebreak',
'Resist Bonebreak Mastery',
'Resist Bonebreak Enhanced Mastery',
'Resist Bonebreak Superior Mastery',
'Resist Disarm',
'Resist Disarm Mastery',
'Resist Disarm Enhanced Mastery',
'Resist Disarm Superior Mastery',
'Resist Dismember',
'Resist Dismember Mastery',
'Resist Dismember Enhanced Mastery',
'Resist Dismember Superior Mastery',
'Resist Knockback',
'Resist Knockback Mastery',
'Resist Knockback Enhanced Mastery',
'Resist Knockback Superior Mastery',
'Resist Knockdown',
'Resist Knockdown Mastery',
'Resist Knockdown Enhanced Mastery',
'Resist Knockdown Superior Mastery',
'Resist Nerve Strike',
'Resist Nerve Strike Mastery',
'Resist Nerve Strike Enhanced Mastery',
'Resist Nerve Strike Superior Mastery',
'Resist Shield Arm Bonebreak',
'Resist Shield Arm Bonebreak Mastery',
'Resist Shield Arm Bonebreak Enhanced Mastery',
'Resist Shield Cleave',
'Resist Shield Cleave Mastery',
'Resist Shield Cleave Enhanced Mastery',
'Resist Through Damage',
'Resist Through Damage Mastery',
'Resist Through Damage Enhanced Mastery',
'Shield Arm Bonebreak',
'Shield Arm Bonebreak Mastery',
'Shield Arm Bonebreak Enhanced Mastery',
'Shield Cleave',
'Shield Cleave Mastery',
'Shield Cleave Enhanced Mastery',
'Shield Cleave Superior Mastery',
'Spiritual Warrior',
'Spiritual Warrior Mastery',
'Spiritual Warrior Enhanced Mastery',
'Subdual',
'Subdual Mastery',
'Subdual Enhanced Mastery',
'Sunder',
'Sunder Mastery',
'Sunder Enhanced Mastery',
'Cast through Weapon',
'Cast through Weapon Mastery',
'Weapon Bond',
'Weapon Proficiency - Single handed (blunt and sharp)',
'Weapon Mastery - Single handed (blunt / sharp)',
'Weapon Enhanced Mastery - Single handed (blunt/sharp)',
'Dagger Proficiency',
'Dagger Mastery',
'Dagger Enhanced Mastery',
'Weapon Proficiency - Double handed (blunt and sharp)',
'Weapon Mastery - Double handed (blunt / sharp)',
'Weapon Enhanced Mastery - Double handed (blunt/sharp)',
'Weapon Attunement (single sharp/blunt; double sharp/blunt; dagger)',
'Class Upgrade - Class Secondary to Primary',
'Class Upgrade - Class Secondary 2 to Primary' ,
'Class Upgrade - Class Secondary 3 to Primary',
'Class Upgrade - Class Secondary 4 to Primary',
'Class Upgrade - Class Secondary 5 to Primary',
'Class Upgrade - Class Secondary 6 to Primary',
'Class Upgrade - Class Secondary 7 to Primary',
'Guild Upgrade - Additional Class Secondary to Primary',
'Guild Upgrade - Additional Class 2 Secondary to Primary',
'Has Purple Magic' ,
'Is Dedicated',]